main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
app_name = "main"

urlpatterns = [
    path('', TemplateView.as_view(template_name='main/home.html'), name='all'),
    path('manage/', views.PersonListView.as_view(), name='list'),
    path('members/add/', views.PersonCreateView.as_view(), name='add'),
    path('members/<int:pk>/delete/', views.PersonDeleteView.as_view(), name='remove'),
    path('members/<int:pk>/update/', views.PersonUpdateView.as_view(), name='update'),
    path('members/send/', views.PersonSendView.as_view(), name='send'),
    path('about/', TemplateView.as_view(template_name='main/about.html'), name='about'),

]

main/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100,validators=[MinLengthValidator(2,'The Name Must Be Atleast 2 Characters')])
    email = models.EmailField(max_length=250)
    group = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hasVoted = models.BooleanField(default=False)
    hasBeenAssigned = models.BooleanField(default=False)

    def __str__(self):
        return self.name

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, UpdateView
from django.views import View
from main.models import Person
from django.conf import settings
from main.forms import PersonForm
import random
from django.core.mail import EmailMessage


# Manage Members In A Group
class PersonListView(View):
    template_name = 'main/people_list.html'

    def get(self, request):
        if request.user.is_authenticated:
            members = Person.objects.filter(group=request.user)
            personForm = PersonForm()
            ctx = {'person_list': members, 'person_form': personForm, 'person_count':len(members)}
            return render(request, self.template_name, ctx)
        else:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))


# POST for adding members
class PersonCreateView(View, LoginRequiredMixin):
    def post(self, request):
        form = PersonForm(request.POST)
        if form.is_valid():
            person = form.save(commit=False)
            person.group = request.user
            person.save()
            return redirect(reverse_lazy('main:list'))
        ctx = {'form': form}
        return render(request, 'main/register.html', ctx)


# Update Member
class PersonUpdateView(UpdateView, LoginRequiredMixin):
    model = Person
    template_name = 'main/person_update.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('main:list')


# Delete Member
class PersonDeleteView(DeleteView, LoginRequiredMixin):
    model = Person
    template_name = 'main/person_delete.html'
    success_url = reverse_lazy('main:list')

    def get_queryset(self):
        print('delete get_queryset called')
        qs = super(PersonDeleteView, self).get_queryset()
        return qs.filter(group=self.request.user)


class PersonSendView(View):
    def get(self, request):
        if request.user.is_authenticated:
            people = Person.objects.filter(group=request.user)
            return render(request, 'main/person_choose.html', {'people': people})
        else:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    def post(self, request):
        groupMembers = Person.objects.filter(group=request.user)
        # add error safety for the line if chosenPerson deosnt exist
        for member in groupMembers:
            generateSecretSanta(member, request.user)
        return render(request, 'main/person_reveal.html')


def generateSecretSanta(currentPerson, group):
    currentPerson = Person.objects.filter(id=currentPerson.id)
    if len(currentPerson) <= 0:
        return None
    else:
        currentPerson = currentPerson[0]

    if currentPerson.hasVoted:
        return 0
    else:
        people = Person.objects.filter(group=group, hasBeenAssigned=False).exclude(id=currentPerson.id)
    if len(people) > 2:
        num = random.randrange(0, len(people) - 1)
        chosenPerson = people[num]
    elif len(people) == 2:
        chosenPerson = people.filter(hasVoted=False)
        if len(chosenPerson) > 0:
            chosenPerson = chosenPerson[0]
    elif len(people) == 1:
        chosenPerson = people[0]
    else:
        return None
    currentPerson.hasVoted = True
    currentPerson.save()
    chosenPerson.hasBeenAssigned = True
    chosenPerson.save()
    sendMail(chosenPerson, currentPerson)
    return chosenPerson


def sendMail(chosenPerson, currentPerson):
    if chosenPerson == 0 or chosenPerson is None:
        return
    else:
        message = EmailMessage(
            from_email='contact@stephenprabhu.com',
            to=[currentPerson.email],
        )
        message.template_id = 'd-874456928cfb4b4d8fa93bbc557a84dc'
        message.dynamic_template_data = {
            "secret_name": chosenPerson.name
        }
        message.send(fail_silently=False)

main/templates/base_home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Easily Set Up A Secret Santa Group">
    <meta name="author" content="Stephen Prabhu">
    <style>
    #homeContent{
       text-align: center;
       font-family: 'Quicksand', sans-serif;
    }
    h3{
        font-family: 'Lobster', cursive;
    }
    body {
        background-image: url('https://stephenprabhu.zd.lu/secretSantaBackground.png');
        background-size: cover;
    }
    .mycard {
        margin: auto;
        width: 50%;
    }
    @media (min-width:1000px) {
      #myFooter {
      position:fixed;
      bottom:0px;
      left: 45%;
      font-family: 'Lobster', cursive;
    }
    }
    @media (max-width:968px) {
      body {
            background-image: url('https://stephenprabhu.zd.lu/secretSantaBackground.png');
            background-size: auto;
        }
        .mycard {
            margin: auto;
            width: 90%;
        }
        #addMemberCard{
          margin-top: 1em;
          margin-bottom: 1em;
        }
        #myFooter {
          margin-top: 2em;
          text-align: center;
          font-family: 'Lobster', cursive;
        }
        #siteVersion{
          display: block;
        }
    }
    
    </style>

<title>Secret Santa Machine</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous"
    >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% block head %} {% endblock %}

</head>
{% load static %}
<body>
<div id="homeContent" class="container">
{% block navbar %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Navbar brand -->
      <a class="navbar-brand" href="{% url 'main:all' %}"><h3>Secret Santa Machine</h3></a>
  
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:all' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:about' %}">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
 {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %}
    <div id="myFooter"  >Created By Stephen. Built With Django</div>

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/about.html
{% extends 'base_home.html' %}

{% block content %}
<h3 style="display: inline;">Secret Santa Machine</h3><span id="siteVersion"><small> Version 1.0</small></span>
<div class="row" style="text-align: center;margin-top: 1em;">
<div class="col-3">

</div>
<div class="col-6">
    <p>Hi, I'm Stephen and I am a web developer. 
        My goal of this web application is to make the secret santa process assigning fun and easy.</p>
    <p>If You have any comments/queries or if you would like to follow my work, here are some links:</p>
    <p>
        <a href="https://stephenprabhu.com/" class="btn btn-sm btn-primary"><i class="fas fa-globe"></i> stephenprabhu.com</a><br>
        <a href="https://github.com/stephenprabhu" class="btn btn-sm btn-primary mt-2"><i class="fab fa-github"></i> GitHub</a><br>
        <a href="https://www.linkedin.com/in/stephen-machado-prabhu-8549277a/" class="btn btn-sm btn-primary mt-2"><i class="fab fa-linkedin-in"></i> LinkedIn</a>
    </p>
</div>
<div class="col-3">
    
</div>

    
</div>

<h5 class="mt-2">Source Code: </h5>
<a class="btn btn-info" href="https://github.com/stephenprabhu/secret-santa-generator"><i class="fab fa-github"></i> GitHub</a>
    <h5 class="mt-2">Background Image:</h5>
    <a class="btn btn-success" href="https://www.freepik.com/vectors/christmas">Christmas vector by freepik</a>
{% endblock %}

main/templates/main/home.html
{% extends "base_home.html" %}

{% block content %}
<h3>Ho Ho Ho, Lets Begin</h3>

<div class="row">
    <div class="col-12 mt-3">
        <a href="{% url 'register' %}" class="btn btn-success"><i class="far fa-snowflake"></i> Create New Group</a>
    </div>
    <div class="col-12 mt-3">
        <a href="{% url 'main:list' %}" class="btn btn-success"><i class="far fa-snowflake"></i> Manage Existing Group</a>
    </div>
      <div class="col-12 mt-3">
        <a href="{% url 'main:about' %}" class="btn btn-success"><i class="fas fa-snowman"></i>  About</a>
    </div>
</div>


{% endblock %}

main/templates/main/people_list.html
{% extends "base_home.html" %}

{% block content %}

<div class="row">
    <div class="col-lg-4">
      <h5>Members In Your Group:</h5>
        {% if person_list %}
        <ul class="list-group mt-3">
        {% for person in person_list %}
        
            <li 
              style="text-align:left" 
              class="list-group-item">
              <span style="float:right"> 
                <button type="button" class="btn btn-sm" data-bs-toggle="modal" data-bs-target="#editPersonModal{{person.id}}">
                  <i style="color:#16a085" class="fas fa-pen"></i>
                </button>
                |
                <button type="button" class="btn btn-sm" data-bs-toggle="modal" data-bs-target="#deletePersonModal{{person.id}}">
                  <i style="color:#e74c3c" class="fas fa-trash-alt"></i>
                </button>
              </span> 
              {{person.name}}<br><small class=" text-muted">{{person.email}}</small> 
           
           </li>
                    <!-- Edit Person Modal -->
          <div style="text-align:left"  class="modal fade" id="editPersonModal{{person.id}}" tabindex="-1" role="dialog" aria-labelledby="editPersonModalLabel{{person.id}}" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editPersonModalLabel{{person.id}}">Edit Person</h5>
                  <button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="POST" action="{% url 'main:update' person.id %}">
                  {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                      <label class="mb-1" for="id_name">Name:</label>
                        <input type="text" name="name" class="form-control" maxlength="100" required id="id_name" value="{{person.name}}">
                    </div>
                    <div class="form-group mt-2">
                      <label class="mb-1" for="id_email">Email:</label>
                        <input type="email" name="email" class="form-control" maxlength="250" required id="id_email" value="{{person.email}}">
                    </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <input type="submit" class="btn btn-primary" value="Submit">
                </div>
              </form>
              </div>
            </div>
          </div>

          <!-- Delete Person Modal -->
          <div class="modal fade" id="deletePersonModal{{person.id}}" tabindex="-1" role="dialog" aria-labelledby="deletePersonModalLabel{{person.id}}" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deletePersonModalLabel{{person.id}}">Confirmation</h5>
                  <button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="POST" action="{% url 'main:remove' person.id %}">
                  {% csrf_token %}
                <div class="modal-body">
                  <h6> Are You Sure You Wish To Delete This Member?</h6>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <input type="submit" class="btn btn-danger" value="Yes, delete.">
                </div>
              </form>
              </div>
            </div>
          </div>

        {% endfor %}
        </ul>
        {% else %}
            No members yet. Try Adding One.
        {% endif %}

    </div>
    {% load crispy_forms_tags %}
    <div class="col-lg-4">
      <div id="addMemberCard" class="card p-2">
        <h5>Add Member:</h5>
        <form class="mt-3" method="POST" action="{% url 'main:add' %}">
            {% csrf_token %}
            <div class="form-group">
              <label class="mb-1" for="id_name">Member Name<span style="color:#e74c3c">*</span>: </label>
              <input type="text" name="name" class="form-control" maxlength="150" id="id_name" required placeholder="John">
          </div>       
          <div class="form-group mt-2">
              <label class="mb-1" for="id_email">Member Email address<span style="color:#e74c3c">*</span>: </label>
              <input type="email" name="email" class="form-control" maxlength="250" id="id_email" required placeholder="john@example.com" aria-describedby="emailHelp">
            <small id="emailHelp" class="form-text text-muted">The member's secret santa info will be sent to this email address</small>
          </div>
            <button type="submit" class="btn btn-success mt-3"><i class="fas fa-plus"></i> Add</button>
        </form>
      </div>
    </div>
    <div class="col-lg-4 text-center">
      <h5>Begin Process:</h5>

        {% load mathfilters %}
{% if person_count >= 3 %}
    Done Adding Members? Begin Generating Secret Santas for everyone. <br>
<button type="button"  data-bs-toggle="modal" data-bs-target="#sendMail" class="btn btn-success">Begin</button>
{% else %}
    To Start The Process, Add At Least {{ 3|sub:person_count }} More People.
{% endif %}
    </div>
</div>

<!-- Send Email Modal -->
<div class="modal fade" id="sendMail" tabindex="-1" role="dialog" aria-labelledby="sendMailLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sendMailLabel">Confirmation</h5>
        <button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>Are You Sure You Wish To Proceed?</p>
          <p>Please click <strong>Yes</strong> only if you are done adding all members</p>
        <form method="POST" action="{% url 'main:send' %}">
             {% csrf_token %}
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            <button type="submit" class="btn btn-primary">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>




{% endblock %}

main/templates/main/person_reveal.html
{% extends "base_home.html" %}

{% block content %}
<h4>Success</h4>
    <h5>YAY! Every member in the group has been sent an email with a name of a secret member from your group.</h5>
    <h6>Please allow 2-4 minutes for the email to arrive in the inbox of each member.</h6>
    <h6>If You Are still unable to see the email, please check the spam or junk folder</h6>

       <a href="{% url 'main:all' %}" class="btn btn-primary">Go Home</a>
{% endblock %}

main/templates/main/person_update.html
{% extends "base_home.html" %}

{% block content %}
<div class="mycard card p-5">
    <form method="POST" action="{% url 'main:update' person.id %}">
        {% csrf_token %}
        {{ form.as_table }}
        <br>
        <a href="{% url 'main:list' %}" class="btn btn-secondary">Cancel</a>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>
    

{% endblock %}

main/templates/main/register.html
{% extends "base_home.html" %}

{% block content %}
<div class="mycard card p-4">
    {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
        {% else %}
            <p> Please Log In To See The Page </p>
        {% endif %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="mb-1" for="id_username">Enter A Username For Your Group:</label>
            <input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username" aria-describedby="usernameHelp" placeholder="Group UserName">
            <small id="usernameHelp" class="form-text ">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
        </div>
        <div class="form-group mt-1">
            <label class="mb-1" for="id_password1">Password:</label>
            <input class="form-control" type="password" name="password1" maxlength="150" autocomplete="new-password" required id="id_password1" aria-describedby="passwordHelp">
            <small id="passwordHelp" class="form-text text-muted">
                <ul style="list-style-type: none;">
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
                </small>
        </div>
        <div  class="form-group">
            <label class="mb-1" for="id_password2">Password (again):</label>
            <input class="form-control" type="password" name="password2" maxlength="150" autocomplete="new-password" required id="id_password2">
        </div>
        <input class="btn btn-success mt-4" type="submit" name="submit" value="Create Group" />
        
    </form>

  <p class="mt-5">Have You Already Created A Group? <a class="btn btn-primary" href="{% url 'main:list' %}">Log In</a> To Add/Delete Members</p>
</div>

{% endblock %}